#!/bin/sh
### BEGIN INIT INFO
# Provides:          nvi
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to recover nvi edit sessions.
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start|restart|force-reload)
    /usr/share/vi/recover
    ;;
  stop|reload)
    ;;
esac

exit 0
